# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5A5CcxvnZwFJJDg2q1Ul8MFGq0OvxjM
"""

import streamlit as st
import yfinance as yf
import pandas as pd
import datetime as dt
from tensorflow.keras.models import load_model
import numpy as np
import pickle

# Load assets
@st.cache(allow_output_mutation=True)
def load_assets():
    with open('scaler.pkl', 'rb') as f:
        scaler = pickle.load(f)
    model = load_model('best_model.h5')
    return scaler, model

scaler, model = load_assets()

# Streamlit page setup
st.title('S&P 500 Stock Price Prediction')

# Fetch S&P 500 tickers
sp500 = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')[0]
sp500['Symbol'] = sp500['Symbol'].str.replace('.', '-')
symbols_list = sp500['Symbol'].tolist()

# Selectbox for user input
selected_symbol = st.selectbox('Choose a stock symbol:', symbols_list)

# Date range selection
start_date = st.date_input('Start date', value=pd.to_datetime("2022-01-01"))
end_date = st.date_input('End date', value=pd.to_datetime("today"))

# Predict button
if st.button('Predict'):
    # Fetch data
    data = yf.download(selected_symbol, start=start_date, end=end_date)
    
    if not data.empty:
        # Preprocess data
        data_filled = data['Close'].fillna(method='ffill').values.reshape(-1,1)
        scaled_data = scaler.transform(data_filled)
        X = []
        for i in range(60, len(scaled_data)):
            X.append(scaled_data[i-60:i, 0])
        X = np.array(X)
        X = np.reshape(X, (X.shape[0], X.shape[1], 1))
        
        # Predict using the model
        predictions = model.predict(X)
        predicted_prices = scaler.inverse_transform(predictions)
        
        # Display the chart of predicted prices
        st.line_chart(predicted_prices.flatten())
        
        # Display predictions
        st.write("Predictions:", predicted_prices[-1])
    else:
        st.error("No data available for the selected stock and date range.")
